### ISSUE TITLE
Touch fails in editor

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-core#54]
Caused by: java.lang.ClassCastException: org.eclipse.jface.text.TextSelection cannot be cast to org.eclipse.jface.viewers.IStructuredSelection
	at org.moflon.core.ui.handler.TouchResourceHandler.execute(TouchResourceHandler.java:26)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 51 more

**Comment by anthonyanjorin** [comment]
What does "eMoflon Git" mean?

**Comment by RolandKluge** [comment]
Was a typo. I meant the 'Touch resource' feature that can be used to trigger incremental builds.
